### ISSUE TITLE
a problem in dataloader code

### ISSUE THREAD

**Issue by ray-peng** [ashutosh1807/PixelFormer#14]
To avoid blank boundaries due to pixel registration
if self.args.dataset == 'nyu':
                if self.args.input_height == 480:
                    depth_gt = np.array(depth_gt)
                    valid_mask = np.zeros_like(depth_gt)
                    valid_mask[45:472, 43:608] = 1
                    depth_gt[valid_mask==0] = 0
                    depth_gt = Image.fromarray(depth_gt)
                else:
                    depth_gt = depth_gt.crop((43, 45, 608, 472))
                    image = image.crop((43, 45, 608, 472))

sorry, I can't understand this code. Could you illustrate it?

**Comment by ashutosh1807** [comment]
These are the standard crop size used for evaluation of NYUV2.

**Comment by ray-peng** [comment]
thank you, i don't notice the condition of 'if'
