### ISSUE TITLE
About the training cost of GPU memory

### ISSUE THREAD

**Issue by lai-pf** [ashutosh1807/PixelFormer#2]
In paper , I note that you use 4 A100 to train PixelFormer in batch_size 8.
And I want to know how many GPU memory used in each A100, because I don't have 4 A100 to train the model.

**Comment by lai-pf** [comment]
Sorry to bother you, I've tried your excellent work, and it run successfully.
And if I change the batch_size from 8 to 4, can this PixelFormer still get good result? have you try batch_size=4 before?
Thanks, your reply will help me a lot

**Comment by ashutosh1807** [comment]
Hi, I did not try training for all epochs with smaller batch size. However, I believe it will lead to some performance drop.
