### ISSUE TITLE
How to train? And, How to use the training result weight?

### ISSUE THREAD

**Issue by EthanChou860314** [ashutosh1807/PixelFormer#6]
I use "python pixelformer/train.py configs/arguments_train_kittieigen.txt"
And I get the "events.out.tfevents.1673256044.dl-Precision-3650-Tower" in ./models/pixelformer_kittieigen/summaries/.
But it can't use to detect
"python3 pixelformer/demo.py --checkpoint_path models/pixelformer_kittieigen/summaries/events.out.tfevents.1673256044.dl-Precision-3650-Tower --input_height 352 --input_width 1120 --dataset kitti --video test.bmp --max_depth 8"

== Load encoder backbone from: None
Traceback (most recent call last):
  File "pixelformer/demo.py", line 203, in loadVideoFile
    self.model = load_model()
  File "pixelformer/demo.py", line 80, in load_model
    checkpoint = torch.load(args.checkpoint_path)
  File "/home/dl/python_venv/Transformer_venv/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/dl/python_venv/Transformer_venv/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x18'.

Q1: Is  "models/pixelformer_kittieigen/summaries/events.out.tfevents.1673256044.dl-Precision-3650-Tower "  a weight?
Q2: How can I use the training result to run the demo code?

**Comment by ashutosh1807** [comment]
The directory ./models/pixelformer_kittieigen/ will also contain the checkpoints for the saved models post-training. You can use those for inference.
